{% set name = "vegspec" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vegspec-{{ version }}.tar.gz
  sha256: 132c1b9f52b44077a9135ca75904feff15339dbfecbe4f20c48c53b05e4cdf8d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - vegspec
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/kthorp/vegspec
  summary: A compilation of vegetative spectral indices and transformations in Python
  dev_url: http://github.com/kthorp/vegspec
  license: SAX-PD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kthorp
